### ISSUE TITLE
Vite throw error of import.meta.env

### ISSUE THREAD

**Issue by mandorakannu** [vitejs/vite-plugin-react#94]
### Describe the bug

I am trying to build a web-app which contains some `.env` data but while start building the app its throw error.
`Error`

`error during build:
SyntaxError: Invalid regular expression: /(?<![\p{L}\p{N}_$]|(?<!\.\.)\.)(process\.env\.NODE_ENV|global\.process\.env\.NODE_ENV|globalThis\.process\.env\.NODE_ENV|__vite_process_env_NODE_ENV|import\.meta\.hot|import\.meta\.env\.VITE_API_KEY|import\.meta\.env\.VITE_API\-HOST|import\.meta\.env\.VITE_API_URL|import\.meta\.env\.BASE_URL|import\.meta\.env\.MODE|import\.meta\.env\.DEV|import\.meta\.env\.PROD|import\.meta\.env\.SSR|import\.meta\.env\.|import\.meta\.env|process\.env\.|global\.process\.env\.|globalThis\.process\.env\.)(?:(?<=\.)|(?![\p{L}\p{N}_$]|\s*?=[^=]))/: Invalid escape
    at new RegExp (<anonymous>)
    at generatePattern (file:///D:/Dev/Projects/covid-19/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:40270:15)
    at definePlugin (file:///D:/Dev/Projects/covid-19/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:40285:28)
    at resolvePlugins (file:///D:/Dev/Projects/covid-19/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:40912:9)
    at async resolveConfig (file:///D:/Dev/Projects/covid-19/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61822:24)
    at async doBuild (file:///D:/Dev/Projects/covid-19/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44358:20)
    at async build (file:///D:/Dev/Projects/covid-19/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44347:16)
    at async CAC.<anonymous> (file:///D:/Dev/Projects/covid-19/node_modules/vite/dist/node/cli.js:808:9)`

I am using .env variables in `Search.tsx`
![env](https://user-images.githubusercontent.com/82162224/214889801-a1a82f8b-aefc-4131-8de1-e57e4fa85213.png)
`package.json`
![package](https://user-images.githubusercontent.com/82162224/214890357-d04be67b-9a44-4570-ad5a-729a345e2190.png)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ksfpab?file=src/components/ui/Search.tsx

### Steps to reproduce

Its throw error only local machine 
`npm run build`

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
    Memory: 1.30 GB / 7.44 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (109.0.1518.61)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.0.1
    vite: ^4.0.0 => 4.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi! What is your node version?
Do you get this for vite dev or vite build?
I think this is an issue with Vite core more than this plugin, but given your node version it's strange

**Comment by mandorakannu** [comment]
My node version is **v18.13.0** and I got the error after `npm run build` 
I am using vite react-app with typescript template.

**Comment by ArnaudBarre** [comment]
Can you reproduce with the vanilla (no framework) template? This would help for a bug report in the core repo

**Comment by mandorakannu** [comment]
I can't because i am not familar with vanilla template.
After deploying on vercel its didn't gives any error.
![build](https://user-images.githubusercontent.com/82162224/214899719-9f827196-532c-4015-a2a9-b583748d97e6.png)

**Comment by ArnaudBarre** [comment]
Yeah there is something particular with your setup.
Please provide [a small reproduction](https://antfu.me/posts/why-reproductions-are-required) so we can help

**Comment by mandorakannu** [comment]
> Yeah there is something particular with your setup. Please provide [a small reproduction](https://antfu.me/posts/why-reproductions-are-required) so we can help

Thank you sir for helping me. I just found out the error.
I used in `.env` file `VITE_API-HOST` instead of `VITE_API_HOST` 😂 and its throw error.
